"""WAF detection by header, cookie and body fingerprinting.

The legacy implementation called ``str(headers).lower()`` which produced
unreliable matches (the ``__str__`` of an httpx ``Headers`` mashes name
and value with no stable separator). This module parses headers and
cookies as structured data and uses precompiled regexes for the few
free-form value matches.

Two public entry points:

* :func:`detect_from_response` is pure and synchronous, easy to test
  against synthetic responses.
* :func:`detect_async` wires the detector to an ``httpx.AsyncClient``
  and an optional :class:`ScopePolicy`.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Final

import httpx

from bounty_agent.core import ScopePolicy, WafDetection
from bounty_agent.logging_setup import audit, get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class WafSignature:
    """Fingerprint for a single WAF vendor."""

    vendor: str
    header_names: tuple[str, ...] = ()
    header_value_patterns: tuple[tuple[str, str], ...] = ()
    cookie_names: tuple[str, ...] = ()
    body_markers: tuple[str, ...] = ()

    def match(self, response: httpx.Response) -> bool:
        headers_lower = {k.lower(): v for k, v in response.headers.items()}

        if any(name.lower() in headers_lower for name in self.header_names):
            return True

        for header, pattern in self.header_value_patterns:
            value = headers_lower.get(header.lower())
            if value and re.search(pattern, value, re.IGNORECASE):
                return True

        if self.cookie_names:
            cookie_names_lower = {cookie.name.lower() for cookie in response.cookies.jar}
            if any(name.lower() in cookie_names_lower for name in self.cookie_names):
                return True

        if self.body_markers:
            body = _safe_text(response).lower()
            if any(marker.lower() in body for marker in self.body_markers):
                return True

        return False


def _safe_text(response: httpx.Response) -> str:
    try:
        return response.text
    except UnicodeDecodeError:
        return ""


DEFAULT_SIGNATURES: Final[tuple[WafSignature, ...]] = (
    WafSignature(
        vendor="Cloudflare",
        header_names=("cf-ray", "cf-cache-status"),
        cookie_names=("__cfduid", "cf_clearance", "__cf_bm"),
        header_value_patterns=(("server", r"cloudflare"),),
    ),
    WafSignature(
        vendor="AWS WAF",
        header_names=("x-amzn-waf-action", "x-amzn-requestid", "x-amz-cf-id"),
        header_value_patterns=(("server", r"awselb|cloudfront"),),
    ),
    WafSignature(
        vendor="Akamai",
        header_names=("akamai-origin-hop", "x-akamai-request-id"),
        header_value_patterns=(("server", r"akamaighost"),),
    ),
    WafSignature(
        vendor="ModSecurity",
        header_names=("x-mod-security-message",),
        body_markers=("ModSecurity", "Mod_Security"),
    ),
    WafSignature(
        vendor="Imperva",
        header_names=("x-iinfo", "x-cdn"),
        cookie_names=("incap_ses",),
    ),
    WafSignature(
        vendor="Sucuri",
        header_value_patterns=(("server", r"sucuri/cloudproxy"),),
        body_markers=("Access Denied - Sucuri Website Firewall",),
    ),
    WafSignature(
        vendor="Wordfence",
        body_markers=("generated by wordfence",),
    ),
)


_BLOCKING_STATUS: Final[frozenset[int]] = frozenset({403, 406, 429, 444})
_BLOCKING_TEXT_MARKERS: Final[tuple[str, ...]] = (
    "Access Denied",
    "Request Blocked",
    "blocked by",
)


def detect_from_response(
    response: httpx.Response,
    signatures: tuple[WafSignature, ...] = DEFAULT_SIGNATURES,
) -> WafDetection:
    """Inspect a response and produce a :class:`WafDetection`.

    Pure, synchronous, no I/O. The same response is used for vendor
    matching and the heuristic ``likely_protected`` flag.
    """
    vendors = [sig.vendor for sig in signatures if sig.match(response)]
    body = _safe_text(response)
    likely_protected = (
        bool(vendors)
        or response.status_code in _BLOCKING_STATUS
        or any(marker in body for marker in _BLOCKING_TEXT_MARKERS)
    )
    return WafDetection(
        detected_vendors=vendors,
        likely_protected=likely_protected,
        status_code=response.status_code,
    )


async def detect_async(
    client: httpx.AsyncClient,
    url: str,
    scope: ScopePolicy | None = None,
    signatures: tuple[WafSignature, ...] = DEFAULT_SIGNATURES,
) -> WafDetection:
    """Fetch ``url`` and detect WAFs from the response."""
    if scope is not None:
        scope.check(url)
    try:
        response = await client.get(url, follow_redirects=True)
    except httpx.RequestError as exc:
        logger.warning("waf.fetch_failed", url=url, error=str(exc))
        audit("waf.detection_failed", url=url, error=str(exc))
        return WafDetection(error=str(exc))

    detection = detect_from_response(response, signatures)
    audit(
        "waf.detected",
        url=url,
        vendors=detection.detected_vendors,
        likely_protected=detection.likely_protected,
        status_code=detection.status_code,
    )
    return detection


__all__ = [
    "DEFAULT_SIGNATURES",
    "WafSignature",
    "detect_async",
    "detect_from_response",
]
